#!/usr/bin/bash

WORKDIR="$HOME/containers/fedora"

MAIN="$HOME/containers"

WORKDIR="$MAIN/fedora"

HOMEUSR="/home/willians"

SERVER="fedora"

NETWORK="webdev-net"

PORTS="8000:8000"


IMAGE="localhost/fedora:42"


HOST="fedora"

mkdir -p "$WORKDIR/dotfiles" "$MAIN/pkg" "$WORKDIR/bak" 

# Para rootless: kill si existe y remover
podman kill "$SERVER" 2>/dev/null || true
podman rm "$SERVER" 2>/dev/null || true


podman run -it --name "$SERVER" --hostname "$SERVER" \
  --hostname "$HOST" \
  --network "$NETWORK" \
  -v "$MAIN/pkg:$HOMEUSR/pkg:Z" \
  -v "$MAIN/Laravel/projects:$HOMEUSR/laravel:Z" \
  -v "$HOME/Dev/proyectos:$HOMEUSR/legacy:Z" \
  -v "$HOME/Dev/ensayos:$HOMEUSR/ensayos:Z" \
  -v "$WORKDIR/backups:$HOMEUSR/backup:Z" \
    --privileged \
$IMAGE

