
# Penthouse Sunset
[colors.primary]
# Gris obsidiana extraído del suelo de mármol y el escritorio de la habitación
background = "#141416" 
#background = "#141416" 
# Blanco cálido atenuado, inspirado en los reflejos suaves de las luces de la ciudad
foreground = "#EAE6E1" 
dim_foreground = "#6B6A6E"

[colors.normal]
black   = "#1C1C1F" # Tono del auto deportivo y los marcos de las ventanas
red     = "#D94E34" # El tono más intenso del atardecer sobre los rascacielos
green   = "#50a27b" # Verde apagado inspirado en los sutiles reflejos de los cristales
yellow  = "#E29543" # Ámbar/Naranja encendido del cielo y las luces de los edificios
blue    = "#608ac1" # Azul grisáceo de las nubes superiores y el río a lo lejos
#blue    = "#50627A" # Azul grisáceo de las nubes superiores y el río a lo lejos
magenta = "#A65B6F" # Tono crepúsculo/violáceo de la transición del cielo
cyan    = "#6BA4A3" # Reflejo frío de las pantallas y el horizonte nublado
white   = "#D1CFCB"

[colors.bright]
black   = "#4A4A4F"
red     = "#F06A50" # Brillo discreto del sol poniéndose en el horizonte
green   = "#3ad789"
yellow  = "#F7AD5B" # El brillo dorado que ilumina el Empire State
blue    = "#6B7F99"
magenta = "#C2778B"
cyan    = "#87BDBA"
white   = "#FFFFFF"