[window]
opacity = 1.0
decorations = "Full"
dynamic_title = true
startup_mode = "Windowed"
padding = { x = 8, y = 8 }



[font.offset]
x = 0
y = 3 # Más espacio vertical para reducir la fatiga en lecturas largas

[colors.primary]
background = "#242424" # Fondo más profundo, elimina el lavado gris
#background = "#1b1b1c" # Fondo más profundo, elimina el lavado gris
#background = "#2f2c29" # Fondo más profundo, elimina el lavado gris
foreground = "#c0bd9e" # Blanco de alta visibilidad, elimina lo opaco
#foreground = "#e9e5e5" # Blanco de alta visibilidad, elimina lo opaco
dim_foreground = "#94A3B8"

[colors.normal]
black   = "#1A1A1E"
red     = "#EF4444" # Colores con más vida para identificarlos sin esfuerzo
green   = "#22C55E"
yellow  = "#EAB308"
blue    = "#3B82F6"
magenta = "#D946EF"
cyan    = "#06B6D4"
white   = "#F5F5F5"

[colors.bright]
black   = "#64748B"
red     = "#F87171"
green   = "#4ADE80"
yellow  = "#FDE047"
blue    = "#60A5FA"
magenta = "#F472B6"
cyan    = "#22D3EE"
white   = "#FFFFFF"

#import = ["~/configs-alacritty/alacritty.toml-obsidian-max-enfoque"]

[font]
# VictorMono para itálicas fluidas y JetBrains para legibilidad técnica
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
#italic = { family = "VictorMono Nerd Font", style = "Italic" }
size = 13 # Ajusta este valor según la pantalla para que no uses zoom


[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false

[terminal]
shell = { program = "/usr/bin/tmux", args = ["new-session", "-A", "-s", "main"] }

[general]
live_config_reload = true
import = []

[env]
TERM = "xterm-256color"

# pegar texto. Alt+V 
[[keyboard.bindings]]
key = "V"
mods = "Alt"
action = "Paste"

