# ~/.config/alacritty/alacritty.toml
# OPTIMIZADO para .zshrc reciente + Fedora Kinoite 2026

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Full"
#decorations = "Buttonless"
#opacity = 0.95
#startup_mode = "Maximized"

[font]
# ✅ Nerd Font para Starship + bling.sh icons
italic = { family = "VictorMono Nerd Font", style = "Italic" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
#bold = { family = "Ubuntu Sans Mono Nerd Font", style = "Bold" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13.2850


[env]
TERM = "xterm-256color"

# Keybindings para tu workflow DevOps/PHP

# Logs largos (Podman/Laravel)
[scrolling]
history = 10000
multiplier = 3

[colors.primary]
# background = "#1a1b26" # Estilo Tokyo Night
foreground = "#F88132"
background = "#171A26"

# Colores Normales: Se usan para el texto estándar y comandos
[colors.normal]
black   = "#32344a"
red     = "#f7768e" # Errores en consola / Git deletes
green   = "#9ece6a" # Éxito / Git adds
yellow  = "#e0af68" # Warnings / Atributos
blue    = "#7aa2f7" # Funciones / IDs
magenta = "#ad8ee6" # Keywords (if, return, export)
cyan    = "#44dfaf" # Strings / Regex
white   = "#787c99"

# Colores Bright: Versiones vibrantes para destacar elementos específicos
[colors.bright]
black   = "#444b6a"
red     = "#ff007c"
green   = "#b9f27c"
yellow  = "#ff9e64" # Constantes / Nombres de clases
blue    = "#7da6ff"
magenta = "#bb9af7"
cyan    = "#0db9d7"
white   = "#acb0d0"


## Tus colores GitHub Dark (perfectos)
#[colors.primary]
#background = "#0d1117"
#foreground = "#c9d1d9"
#bright_foreground = "#f0f6fc"
#
#[colors.normal]
#black = "#0d1117"
#red = "#ff7b72"
#green = "#7ee787"
#yellow = "#d29922"
#blue = "#58a6ff"
#magenta = "#d2a8ff"
#cyan = "#39c5cf"
#white = "#c9d1d9"
#
#[colors.bright]
#black = "#484f58"
#red = "#ff7b72"
#green = "#7ee787"
#yellow = "#d29922"
#blue = "#58a6ff"
#magenta = "#bc8cff"
#cyan = "#39c5cf"
#white = "#f0f6fc"

[terminal.shell]
program = "/usr/bin/tmux"                    # ← Alacritty llama tmux
args = ["new-session", "-A", "-s", "main"] # ← Crea/une sesión main
